### ISSUE TITLE
提交链接不安全，估计没有走 HTTPS

### ISSUE THREAD

**Issue by weaming** [SaltyLeo/IPFS-Markdown-Post#2]

**Comment by SaltyLeo** [comment]
能截图看一下吗？demo的配置是全程https。

**Comment by weaming** [comment]
![image](https://user-images.githubusercontent.com/10275711/99161591-e93d0000-272e-11eb-8922-7b42a0be7c87.png)

```
curl 'https://post.ipfs.uno/post' \
  -H 'authority: post.ipfs.uno' \
  -H 'cache-control: max-age=0' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'origin: https://post.ipfs.uno' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4315.5 Safari/537.36' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-user: ?1' \
  -H 'sec-fetch-dest: document' \
  -H 'referer: https://post.ipfs.uno/' \
  -H 'accept-language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7' \
  -H 'cookie: session=eyJjc3JmX3Rva2VuIjoiMTY4MDA5YzNkMzY5Yjc4MDQ1MjY4ZDEzZGUwMDllYjJkNTVkOWM1NyJ9.X66guA.TI_XsQTbxXj_6N0P5MDx48bFARk' \
  --data-raw 'checkbox1=on&post=%3Cdiv+class%3D%22easy-markdown%22%3E%3Cp%3Ehttps%3A%2F%2Fipfs.drink.cafe%2Fipfs%2FQmVVh6SBNzt5qFxHSX6eZx67vehWpnHVbdr225wqb3zC4R%3C%2Fp%3E%3C%2Fdiv%3E&csrf_token=IjE2ODAwOWMzZDM2OWI3ODA0NTI2OGQxM2RlMDA5ZWIyZDU1ZDljNTci.X7CUtQ.hKsbIOL9Mfflfnx48DoMwEhZIEU&mark_raw=' \
  --compressed
```

**Comment by weaming** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=post.ipfs.uno

**Comment by weaming** [comment]
> https://www.ssllabs.com/ssltest/analyze.html?d=post.ipfs.uno

Best practices outlined in RFC-7525 give reasons why it is discouraged to use protocol TLS 1.0 and TLS 1.1. PCI-DSS recommends users to switch from protocol TLS 1.0 and adopt protocol TLS 1.2+.

**Comment by SaltyLeo** [comment]
我这里测试没有出现和你一样的证书错误问题，我尝试在服务端去除了TLS1.0、1.1的支持仅保留1.2、1.3，但没有检查到变化。

或许是客户端浏览器SNI支持的问题？

**Comment by weaming** [comment]
![image](https://user-images.githubusercontent.com/10275711/99181414-5d949500-2769-11eb-896a-a7b0362fa979.png)
![image](https://user-images.githubusercontent.com/10275711/99181522-0d6a0280-276a-11eb-93db-ca1460e55f02.png)
这里不知为何混入了一个 HTTP

**Comment by weaming** [comment]
> ![image](https://user-images.githubusercontent.com/10275711/99181414-5d949500-2769-11eb-896a-a7b0362fa979.png)
> ![image](https://user-images.githubusercontent.com/10275711/99181522-0d6a0280-276a-11eb-93db-ca1460e55f02.png)
> 这里不知为何混入了一个 HTTP

![image](https://user-images.githubusercontent.com/10275711/99181580-486c3600-276a-11eb-87c4-f4bddf429580.png)
是这个重定向导致的

**Comment by SaltyLeo** [comment]
好的，已经修复了这个问题，在web.py写死https跳转就好了。

[https://github.com/SaltyLeo/Post-Pages-to-IPFS/commit/a53544afa899466a8b90f000c50ff8542284847a](https://github.com/SaltyLeo/Post-Pages-to-IPFS/commit/a53544afa899466a8b90f000c50ff8542284847a)
