### ISSUE TITLE
有没有测试连接，我想看下IPFS生成后的连接

### ISSUE THREAD

**Issue by anarckk** [SaltyLeo/IPFS-Markdown-Post#3]

**Comment by SaltyLeo** [comment]
你发布的文章链接，就是【发布状态检查】页里面每个网关的超链接。

>有 ✅ 的，说明该网关已经缓存了你刚刚发布的页面，点击网关名称即可访问。
有 ⚠️ 的，说明该网关在中国大陆访问困难。
